#!/usr/local/bin/python3
"""AB1 icon lane: emit js/icons-data.js - the data-URI icon registry
(window.WH_ICONS, id -> data:image/png;base64,...). Q4 delivery format.

Usage: /usr/local/bin/python3 tools/io_icon_registry.py
"""
import base64, os

ROOT = '/tmp/wh-worldfeat'
ICONS = os.path.join(ROOT, 'prototype', 'js', 'icons')
OUT = os.path.join(ROOT, 'prototype', 'js', 'icons-data.js')

def main():
    ids = sorted(f[:-4] for f in os.listdir(ICONS) if f.endswith('.png'))
    lines = ['// AB1 icon registry (IO asset lane 2026-10-06): id -> data URI.',
             '// Generated by tools/io_icon_registry.py from prototype/js/icons/*.png',
             '// 48x48, pixel register (NEAREST + 5-bit). Consumers: belt slots,',
             '// consumables, CHARACTER tab, inventory grid, buff chips, picker.',
             'window.WH_ICONS = {']
    for icon_id in ids:
        b = open(os.path.join(ICONS, f'{icon_id}.png'), 'rb').read()
        uri = 'data:image/png;base64,' + base64.b64encode(b).decode()
        lines.append(f'  {icon_id}: "{uri}",')
    lines.append('};')
    open(OUT, 'w').write('\n'.join(lines) + '\n')
    print('wrote', OUT, f'({len(ids)} icons, {os.path.getsize(OUT)} bytes)')

if __name__ == '__main__':
    main()